language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t abcdevelop/docker-react -f Dockerfile.dev .

script:
  #- docker run abcdevelop/docker-react yarn test -- --coverage
  - docker run -e CI=true abcdevelop/docker-react yarn test
  