language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t abcdevelop/docker-react -f Dockerfifle.dev .



script:
  - docker run -e CI=true abcdevelop/docker-react yarn test





  