language: generic
sudo: required
services:
  - docker

#before_install:
#  - docker build -t abcdevelop/docker-react -f Dockerfile.dev .

#script:
  #- docker run abcdevelop/docker-react yarn test --coverage
#  - docker run -e CI=true abcdevelop/docker-react yarn test
  #- docker run -e CI=true abcdevelop/docker-react npm run test

#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-1"
#  app: "docker-react"
#  env: "DockerReact-env"
#  bucket_name: "elasticbeanstalk-us-east-1-169521840923"
#  bucket_path: "docker-react"
#  on:
#    branch: master
#access_key_id: "$AWS_ACCESS_KEY"
#secret_access_key: 
#  secure: "$AWS_SECRET_KEY"
#access_key_id: 
#  secure: $AWS_ACCESS_KEY
#secret_access_key:
#  secure: $AWS_SECRET_KEY
#access_key_id: 
  #secure: $AWS_ACCESS_KEY

before_install:
  - docker build -t $DOCKER_ID/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true $DOCKER_ID/docker-react-test yarn test

after_success:
  - docker build -t $DOCKER_ID/docker-react .
  # Log in to the docker CLI
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  # Take those images and push them to docker hub
  - docker push $DOCKER_ID/docker-react
  